import type { Metadata } from "next";
import { Shadows_Into_Light_Two, Homemade_Apple } from "next/font/google";
import "./globals.css";

const shadowsIntoLightTwo = Shadows_Into_Light_Two({
  variable: "--font-shadows-into-light-two",
  subsets: ["latin"],
  weight: "400",
});

const homemadeApple = Homemade_Apple({
  variable: "--font-homemade-apple",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${shadowsIntoLightTwo.variable} ${homemadeApple.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
